### ISSUE TITLE
Gradients issues

### ISSUE THREAD

**Issue by guestywaste** [airbnb/lottie-web#1241]
Hi Guys.

A few months ago I animated some pre loaders with gradients changes. its was working just fine using lottie, now after 4 months I've reopened the file and made some updates (no colour changes) and no none of the gradients
[Pre_Loader_may_v4c.aep.zip](https://github.com/airbnb/lottie-web/files/2389521/Pre_Loader_may_v4c.aep.zip)
 are working, im just getting solid colours, any help would be awesome.

**Comment by bodymovin** [comment]
Hi, thanks for reporting.
It'll be fixed on the next deploy.

**Comment by guestywaste** [comment]
Thanks for the quick reply, any idea when the next deploy will be?

Thanks

Matthew

**Comment by bodymovin** [comment]
I haven't done a new full build but I just pushed the player on the `build/player` folder with the fix. You can get it from there.

**Comment by guestywaste** [comment]
Thanks for that, but it still hasn't fixed the issue, we ended up using a past version on BM. Has the player been updated for lottie? as the gradients are still not showing correctly. Thanks

**Comment by bodymovin** [comment]
Can you share a link where it is still failing?
With yersterday's release it should be working fine.

**Comment by bodymovin** [comment]
uploaded

**Comment by guestywaste** [comment]
Hi.  https://www.lottiefiles.com/share/Rn1RdS
It should be going from blue to a green/yellow gradient and the red should not be there

Thanks

**Comment by bodymovin** [comment]
The lottiefiles web has an old version of the player
