### ISSUE TITLE
Fail to refer to the right keyPath using lottie-api 

### ISSUE THREAD

**Issue by shirley737** [airbnb/lottie-web#2081]
Hello @bodymovin , 

I tried to dynamically change the color of a layer by using API.getKeyPath() method, but couldn't successfully achieve my goal. Is my way of referring keypath correct? 

![image](https://user-images.githubusercontent.com/44116904/78615322-053a0400-7826-11ea-8c85-decb871605d8.png)

My code: 
```
      var anim1 = lottie.loadAnimation(animation1);
      var animationAPI = lottie_api.createAnimationApi(anim1);
      var animkp = animationAPI.getKeyPath(
        "02 - Indeterminate Loader to Check Isolated V2,Circle Fill,Contents,Fill 1,Color"
      );
      animationAPI.addValueCallback(animkp, function () {
        return [0.1, 0.2, 0.3, 1];
      });
```

Thank you so much!

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation? a codepen for example?

**Comment by shirley737** [comment]
Hello @bodymovin, 
codepen.zip](https://github.com/airbnb/lottie-web/files/4465604/codepen.zip)

Here are my example folders which is similar to the one I mentioned. Not sure how to link external .js file on codepen and will just attach here. 

Thank you so much for your help! 

<img width="524" alt="Screen Shot 2020-04-10 at 11 24 38 AM" src="https://user-images.githubusercontent.com/44116904/79056534-540fe100-7c0c-11ea-95fa-ea8f2b838fd0.png">
Here is the picture and I think the keypath is (Waves (3),Contents,Fill 1, Color), but cannot change the color...

**Comment by bodymovin** [comment]
hi, I pushed a new version which I think should solve the issue.
But keep in mind that you need to start the API instance after the animation has been loaded, so you probably want to do something like:
```js
var anim1 = lottie.loadAnimation(animation1);
      anim1.addEventListener('DOMLoaded', function() {
        var animationAPI = lottie_api.createAnimationApi(anim1);
        var animkp = animationAPI.getKeyPath("Waves (3),Contents,Fill 1,Color");
        animationAPI.addValueCallback(animkp, function () {
          return [0.1, 0.2, 0.3, 1];
        });
        anim1.play();
      })
```

**Comment by shirley737** [comment]
Hi @bodymovin, thanks for trying to solve it! I updated my API source and add an event listener, unfortunately I still cannot change the color by using the Lottie API. Is my way of definining the keypath correct or maybe other issues? 

Thanks again! 
[codepen.zip](https://github.com/airbnb/lottie-web/files/4465642/codepen.zip)

**Comment by shirley737** [comment]
Hi @bodymovin! I think it worked today as I tried. Thank you!

**Comment by pratikbendale** [comment]
@shirley737 
can you share your working code
or can you help me on following
https://github.com/airbnb/lottie-web/issues/2298
