### ISSUE TITLE
Hold frames and repeater – incorrect playback / glitches

### ISSUE THREAD

**Issue by woozygoozy** [airbnb/lottie-web#2493]
Hi, so I made this animation where there are three stacks of coins that grow and then disappear of screen in the end

I did this using three coins and then I added a repeater to each and animated the number of copies, using hold frames (so they don't fade in but just appear... 

when I play back the lottie - the first play through is ok, but the second playthrough (on loop) gets glitchy with coins appearing to animate backwards...

[3 Profit Animation.json.zip](https://github.com/airbnb/lottie-web/files/6125451/3.Profit.Animation.json.zip)

Please let me know if this is some sort of a limitation / unsupported feature in Bodymovin/Lottie

Thank you in advance!

**Comment by bodymovin** [comment]
hi, can you share a reduced version of the issue with the .aep project?

**Comment by woozygoozy** [comment]
here - any suggestions would be greatly appreciated!
[Anim1.3.aep.zip](https://github.com/airbnb/lottie-web/files/6138275/Anim1.3.aep.zip)

**Comment by woozygoozy** [comment]
also if you have a moment - I was wandering if there is any way to create a counter that counts up, using a an expression of some sort... or maybe mapping a slider to the text output... and then animating a slider... any suggestions rather than animating it manually....

**Comment by bodymovin** [comment]
I found the issue, it will be fixed on the next release.
Thanks for your help!

**Comment by woozygoozy** [comment]
Awesome! Thanks for that! 

so would it be too rude to ask for the approximate ETA on that release?

**Comment by bodymovin** [comment]
this should be fixed on version 5.7.7

**Comment by woozygoozy** [comment]
Hi Hernan, upon testing it still does not work as expected... here is the project file again and the screen recording of the issue...

https://user-images.githubusercontent.com/44062706/115125254-d4da8900-9f94-11eb-92df-22f32f4891aa.mp4
[Profit.aep.zip](https://github.com/airbnb/lottie-web/files/6329931/Profit.aep.zip)
