### ISSUE TITLE
Problem with Text Alignment

### ISSUE THREAD

**Issue by fabsoldano** [airbnb/lottie-web#783]
Hi everybody,

some months ago I've exported a json animation with bodymovin and everything looks good on Lottie. Some days ago I've realized that the same animation has an alignment problem with a text.
I've read other issues here on github and many answers explain to update the version of Bodymovin or to use the same width and height dimension in all the compositions. The problem is still the same.

Here's the preview of what I see:
https://www.lottiefiles.com/share/CHl1tB

Here's the correct text alignment:
![Image of Screen](https://preview.ibb.co/bxXHFR/Schermata_2017_12_21_alle_15_49_35.png)

AE source file:
https://drive.google.com/open?id=1UsefJ8NUYb2_b0kAxugs5dYiSxOH1DAb

* **Browser and Browser Version:**
Google Chrome: 62.0.3202.94

* **After Effects Version:**
AE CC 2018 15.0.0

* **Bodymovin Version:**
5.0.6

Anybody had this problem?

Thank you,
Fab

**Comment by bodymovin** [comment]
I think this should be working in the latest version.

**Comment by fabsoldano** [comment]
@bodymovin I've just tried with the last version (5.1.1.) but I still have the same problem.
Someone have some suggestion how to solve this problem? :(

https://www.lottiefiles.com/share/kte1kF

Thank you,
Fab

**Comment by perky** [comment]
I can reproduce this bug:

Create a text layer in AE by selecting Layer/New/Text.
Create another text layer by selecting the Horizontal Type Tool and dragging a text box in the composition.
Position both text layers to that they are aligned.

When you render via bodymovin you will see that the 2nd text layer has been shifted to the right and is now out of alignment with the 1st layer.

**Comment by fabsoldano** [comment]
Thank you so much @perky.
I've created a new text layer without the text box and now it is working 👍
