### ISSUE TITLE
Animation doesn't work in firefox

### ISSUE THREAD

**Issue by jlemoser** [airbnb/lottie-web#892]
Hello, So I have a bodymovin animation acting as a pre-loader to my website but for some reason it doesn't appear to work on firefox, it works perfectly on Chrome, glitches a little on safari but for firefox it completely doesn't show up. 

Here is a link to my website:
www.jlemoser.com
(The pre-loader is only set on the homepage)

my Firefox version: 49.0.2

So I was wondering if this is a solvable issue and any help would be appreciated.
Thanks,
-Joey

**Comment by bodymovin** [comment]
can you update the player to the latest version?
Version 5.1.8 should fix the issue.

**Comment by jlemoser** [comment]
I updated the player, deleted the cache, but it still doesn't work.
heres the html code I'm using for it to appear:
<!DOCTYPE html>


<script src="http://jlemoser.com/wp-content/uploads/lottie.js"></script>
   


<body>
<div id="lottie"></div>

<script>
    var anim;
    var elem = document.getElementById('lottie');
    var animData = {
        container: elem,
        renderer: 'svg',
        loop: false,
        autoplay: true,
        rendererSettings: {
        progressiveLoad:false,},
        path: 'http://jlemoser.com/wp-content/uploads/logo.json'
    };
    anim = lottie.loadAnimation(animData);
</script>
</body>
</html>

**Comment by bodymovin** [comment]
Can you check firefox dev console to see if there is any error there?

**Comment by jlemoser** [comment]
I get a typeError: invalid arguments 
e()
jquery.js:1
DashProperty()
jquery.js:1
SVGStrokeStyleData()
jquery.js:1
SVGShapeElement.prototype.createStyleElement()
jquery.js:4
SVGShapeElement.prototype.searchShapes()
jquery.js:5
SVGShapeElement.prototype.searchShapes()
jquery.js:5
SVGShapeElement.prototype.createContent()
jquery.js:4
t.initElement()
jquery.js:4
SVGShapeElement()
jquery.js:1
SVGRenderer.prototype.createShape()
jquery.js:4
BaseRenderer.prototype.createItem()
jquery.js:4
SVGRenderer.prototype.buildItem()
jquery.js:4
BaseRenderer.prototype.buildAllItems()
jquery.js:4
ICompElement.prototype.initElement()
jquery.js:4
SVGCompElement()
jquery.js:1
SVGRenderer.prototype.createComp()
jquery.js:4
BaseRenderer.prototype.createItem()
jquery.js:4
SVGRenderer.prototype.buildItem()
jquery.js:4
BaseRenderer.prototype.buildAllItems()
jquery.js:4
ICompElement.prototype.initElement()
jquery.js:4
SVGCompElement()
jquery.js:1
SVGRenderer.prototype.createComp()
jquery.js:4
BaseRenderer.prototype.createItem()
jquery.js:4
SVGRenderer.prototype.buildItem()
jquery.js:4
BaseRenderer.prototype.buildAllItems()
jquery.js:4
BaseRenderer.prototype.initItems()
jquery.js:4
AnimationItem.prototype.checkLoaded()
jquery.js:5
t()
jquery.js:5
bound t()
self-hosted
AnimationItem.prototype.waitForFontsLoaded</<()
jquery.js:5
AnimationItem.prototype.configAnimation()
jquery.js:5
AnimationItem.prototype.setParams/r.onreadystatechange()
jquery.js:5

**Comment by bodymovin** [comment]
that should be fixed in version 5.1.8
can you call lottie.version in the console to verify the player version?

**Comment by jlemoser** [comment]
Sorry, but how do I do that?

**Comment by bodymovin** [comment]
It's probably some caché. I see it fine here.

**Comment by jlemoser** [comment]
Okay cool, I reloaded the new version as a different name and relinked it and it worked.
Thanks for the help and quick response!
